### ISSUE TITLE
GPL 3.0 license is unfortunate.

### ISSUE THREAD

**Issue by rerdavies** [leepenney/markdown-gallery#1]
By my reading, GPL 3.0 is incompatible with my MIT-licensed project.  GPL 3.0 licensing is difficult enough. Fathoming how GPL 3.0 would attach to the rest of the project is incomprehensible.

At least CC-BY-SA could be satisfied by a slug line at the end of the page on which your project is used.

MIT, BSD would be most workable. (Happy to give you a credit on the project's About dialog).

**Comment by leepenney** [comment]
There you go, switched to MIT. Which should be more permissive.
